### PR TITLE
Moving <style> inside <template> and <script> inside <dom-module> and Polymer version update

### PR DESCRIPTION
**Pull request by srikkbhat**
As title.

### CODE REVIEW

**Comment by notwaldorf** [comment]
Would you mind bumping the polymer dependency version to `1.1.0`, and squashing your commits, please?

**Comment by srikkbhat** [comment]
Can you please check now?

**Comment by notwaldorf** [comment]
Sure, but can you still squash your commits, please? :)

**Comment by srikkbhat** [comment]
I see only one commit '73cdfac' part of this pull request.  If that does not meet your requirement, can you please be more elaborate on what you are looking for?

**Comment by notwaldorf** [comment]
Oh, all good! Thanks!

**Comment by srikkbhat** [comment]
Thanks!

**Pull request merged**
